import Header from "./_components/header";

export const metadata = {
  title: "Blog Ekhlasur Rahaman" + " | SordarIT",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return (
    <body className="flex h-screen">
      <Header />
      {children}
    </body>
  );
}
